# Generated by Django 6.0.5 on 2026-07-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_add_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightentry',
            unique_together=set(),
        ),
    ]
