version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
      - wger_sqlite_data:/var/lib/wger
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local_dev
      - PYTHONUNBUFFERED=1
      - DJANGO_DB_DATABASE=/var/lib/wger/database.sqlite
      - CSRF_TRUSTED_ORIGINS=https://onyx.francescoadreani.dev,http://onyx.francescoadreani.dev
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  wger_sqlite_data:
