# Generated by Django 6.0.5 on 2026-07-15 10:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0040_alter_exercise_license_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltranslation',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='description_source',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(40)], verbose_name='Description (Source)'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='description_source',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(40)], verbose_name='Description (Source)'),
        ),
        migrations.CreateModel(
            name='CalisthenicsExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='exercisedb', max_length=100)),
                ('source_exercise_id', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.JSONField(default=list)),
                ('body_part', models.CharField(blank=True, max_length=100, null=True)),
                ('target_muscle', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_muscles', models.JSONField(default=list)),
                ('equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('discipline', models.CharField(default='calisthenics', max_length=100)),
                ('movement_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_family', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('is_unilateral', models.BooleanField(default=False)),
                ('is_static_hold', models.BooleanField(default=False)),
                ('is_compound', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('demo_media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercises',
                'indexes': [models.Index(fields=['discipline'], name='exercises_discipl_4e20da_idx'), models.Index(fields=['skill_family'], name='exercises_skill_f_de74c1_idx'), models.Index(fields=['level'], name='exercises_level_0b083a_idx'), models.Index(fields=['is_published'], name='exercises_is_publ_7f61ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExerciseImportRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='exercisedb', max_length=100)),
                ('source_exercise_id', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exercise_import_raw',
                'unique_together': {('source', 'source_exercise_id')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='exercises.calisthenicsexercise')),
            ],
            options={
                'db_table': 'exercise_tags',
                'indexes': [models.Index(fields=['tag'], name='exercise_ta_tag_b58a21_idx')],
                'unique_together': {('exercise', 'tag')},
            },
        ),
    ]
