# Generated by Django 6.0.5 on 2026-07-30 14:14

import wger.gallery.models.image
import wger.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_date_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', help_text='Only PNG, JPEG and WebP formats are supported', upload_to=wger.gallery.models.image.gallery_upload_dir, validators=[wger.utils.images.validate_image_static_no_animation], verbose_name='Image', width_field='width'),
        ),
    ]
