# Generated by Django 6.0.5 on 2026-07-16 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_userprofile_birthdate_alter_userprofile_height'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calories_goal',
            field=models.PositiveIntegerField(default=680, verbose_name='Daily burned calories goal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='steps_goal',
            field=models.PositiveIntegerField(default=16000, verbose_name='Daily steps goal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='water_goal',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='Daily water goal (L)'),
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('steps', models.PositiveIntegerField(default=0, verbose_name='Steps')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Calories')),
                ('water', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Water (L)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Daily activity',
                'verbose_name_plural': 'Daily activities',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
