# Generated by Django 6.0.5 on 2026-07-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_userprofile_calories_goal_userprofile_steps_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80', max_length=500, verbose_name='Avatar URL'),
        ),
    ]
