# Generated by Django 6.0.5 on 2026-07-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='needs_password_change',
            field=models.BooleanField(default=False, verbose_name='Needs password change'),
        ),
    ]
