# Generated by Django 6.0.5 on 2026-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile_needs_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('beginner', '1-2 times/week'), ('intermediate', '3-4 times/week'), ('advanced', '5+ times/week')], max_length=12, verbose_name='Physical activity level'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            # Defaults to True: existing accounts are treated as already
            # onboarded. Genuine sign-ups are flipped to False in
            # WgerAccountAdapter.save_user().
            field=models.BooleanField(default=True, verbose_name='Onboarding completed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Target body weight'),
        ),
    ]
