# Generated by Django 6.0.5 on 2026-07-19 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_alter_workoutlog_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutsession',
            unique_together={('date', 'user', 'routine', 'day')},
        ),
    ]
