# Generated by Django 6.0.5 on 2026-07-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_alter_workoutsession_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutsession',
            unique_together=set(),
        ),
    ]
