# Generated by Django 6.0.5 on 2026-07-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_date_alter_image_image'),
        ('manager', '0030_alter_workoutsession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='condition_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='gallery.image'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('interrupted', 'Interrupted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='current_week',
            field=models.IntegerField(default=1, verbose_name='Current week'),
        ),
        migrations.AddField(
            model_name='routine',
            name='total_weeks',
            field=models.IntegerField(default=4, verbose_name='Total weeks'),
        ),
    ]
