# Generated by Django 6.0.5 on 2026-07-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_workoutsession_condition_photo_workoutsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='impression',
        ),
    ]
