# Generated by Django 6.0.5 on 2026-08-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_remove_workoutsession_impression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='category',
            field=models.CharField(blank=True, choices=[('calisthenics', 'Calisthenics'), ('strength', 'Strength'), ('hypertrophy', 'Ipertrofia'), ('cardio', 'Cardio'), ('powerlifting', 'Powerlifting'), ('crossfit', 'CrossFit'), ('mobility', 'Mobilità')], default='calisthenics', max_length=50, verbose_name='Category'),
        ),
    ]
